name: Scheduled Algo Trading Run

on:
  schedule:
    # Runs at 3:40 UTC (9:10 IST) every weekday (Mon-Fri)
    - cron: '40 3 * * 1-5'
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r algo_trading/scripts/live_strategy/requirements.txt || pip install pandas numpy aiohttp pyotp


      - name: Run trading bot
        run: |
          python algo_trading/scripts/live_strategy/straddle_strategy_fallback.py
